name: Build
on:
  - push

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE: 'node'
      TAG: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
      LATEST_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build branch
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build latest
        if: github.ref == 'refs/heads/${{ inputs.defaultBranch }}'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
